chore: remove isH5 from theme-default
umijs/dumi pull request #1287
Opened 2022-11-18 17:53 UTC by xiaohuoni

### 🤔 这个变动的性质是？/ What is the nature of this change?

- [ ] 新特性提交 / New feature
- [ ] bug 修复 / Fix bug
- [ ] 样式优化 / Style optimization
- [ ] 代码风格优化 / Code style optimization
- [ ] 性能优化 / Performance optimization
- [ ] 构建优化 / Build optimization
- [ ] 网站、文档、Demo 改进 / Website, documentation, demo improvements
- [ ] 重构代码或样式 / Refactor code or style
- [ ] 测试相关 / Test related
- [x] 其他 / Other

### 🔗 相关 Issue / Related Issue

### 💡 需求背景和解决方案 / Background or solution

一些代码的修改建议 

### 📝 更新日志 / Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

2022-11-19 14:20 UTC, PeachScript commented on suites/theme-mobile/src/builtins/Previewer/index.tsx
> +          {props.iframe ? (
mobile 要不要默认 iframe 为 true，可配置为 false？

2022-11-19 14:20 UTC, PeachScript commented on suites/theme-mobile/src/builtins/Previewer/index.tsx
> +      {!isH5 && (
isH5 为啥从 hd 配置来判断？我理解用户安装了 mobile 应该是希望默认用 mobile 来渲染，可以支持给 demo 的 FrontMatter 配置 mobile: false 来回退到 PC 模式？

2022-11-20 12:28 UTC, PeachScript commented
需要发个版，revert 的部分我单独提交了哈：https://github.com/umijs/dumi/commit/560c4d407f165081a5434e3fd5279d042d8a19e2

2022-11-21 01:43 UTC, xiaohuoni commented on suites/theme-mobile/src/builtins/Previewer/index.tsx
> +          {props.iframe ? (
看行为 iframe 本来就默认为 true?

2022-11-21 02:35 UTC, PeachScript approved these changes
+1

2022-11-21 02:47 UTC, PeachScript requested changes

2022-11-21 02:47 UTC, PeachScript commented on suites/theme-mobile/src/builtins/Previewer/index.tsx
> +    <div
看了下整体框架似乎可以复用默认的 Previewer？这个思路看看行不行得通：
1. 默认的 previewer 支持传入 className，通过 mobile 标记决定是否传入
2. mobile 的 className 通过 flex 来修改渲染排版，示意：
![图片](https://user-images.githubusercontent.com/5035925/202951881-04688df5-f0da-4d65-9691-ce4540b0443a.png)
3. 传给默认 Previewer 的 props.iframe 永远为 false，通过 props.children 来控制 Device 的展示与否，伪代码：
```tsx
const MobilePreviewer = () => {
  const demo = mobile ? <Device src={props.demoUrl} /> : props.children;

  return <Previewer {...props} className="dumi-mobile-previewer" iframe={false}>{demo}</Previewer>
}
```

看起来 mobile 不需要支持 iframe false 了？除非有要套 Device 又不用 iframe 渲染的需求

2022-11-21 03:57 UTC, xiaohuoni commented on suites/theme-mobile/src/builtins/Previewer/index.tsx
> +    <div
哼，不是你不让我复用的嘛（委屈）

2022-11-21 04:50 UTC, PeachScript commented on suites/theme-mobile/src/builtins/Previewer/index.tsx
> +    <div
> 哼，不是你不让我复用的嘛（委屈）

我其实是指不能让默认的 Previewer 感知到 h5，还是要复用的[抱大腿]

2022-11-21 07:53 UTC, xiaohuoni commented on suites/theme-mobile/src/slots/Device/index.less
> +  // border-left: dashed 1px #e6e6e6;
```suggestion
```

2022-11-27 08:21 UTC, PeachScript commented on suites/theme-mobile/src/builtins/Previewer/index.less
> +  @media only screen and (max-width: 1440px) {
断点可以用 variables 里的值，保持统一：https://github.com/umijs/dumi/blob/0dbcead65aa2987500f79e6f9b09d8c6641ed952/src/client/theme-default/styles/variables.less#L21

另外设备的宽高比要不要统一交给 Previewer 来控制，现在是 Device 那边控制宽度，这边控制高度，统一在 Previewer 里控制未来还可以提供 select 切换设备类型

2022-11-27 08:21 UTC, PeachScript commented on suites/theme-mobile/src/builtins/Previewer/index.less
> +    width: 100%;
去掉 width 会影响样式么

2022-11-27 08:21 UTC, PeachScript commented on suites/theme-mobile/src/builtins/Previewer/index.less
> +  @media only screen and (max-width: 1440px) {
还有个问题是响应式的方案，手机端访问的时候怎么展示比较好呢，默认只展示 demo、点按钮后把 demo 切换成源代码？

2022-12-01 13:09 UTC, xiaohuoni commented on suites/theme-mobile/src/builtins/Previewer/index.less
> +  @media only screen and (max-width: 1440px) {
我的想法是，手机端的访问了，就默认转到 gallery 只看 demo ，不看文档。或者和 pc 端的响应式同步。

2022-12-01 13:32 UTC, xiaohuoni commented on suites/theme-mobile/src/builtins/Previewer/index.less
> +    width: 100%;
看起来不会

2022-12-01 13:41 UTC, xiaohuoni commented on suites/theme-mobile/src/builtins/Previewer/index.less
> +  @media only screen and (max-width: 1440px) {
当前的效果。如果是手机端，源码放到 demo 下面，看看要不要把显示源码的按钮加回来。
![image](https://user-images.githubusercontent.com/11746742/205067180-8ed470c4-1465-4205-86db-d05b08fd67f0.png)

2022-12-14 10:24 UTC, xiaohuoni commented
👍
（我觉得还行，右侧确实还是有点怪！）

2022-12-15 02:52 UTC, PeachScript commented
> 👍 （我觉得还行，右侧确实还是有点怪！）

那就先这样，右侧如果是正儿八经的组件应该还好 👀

2022-12-15 03:20 UTC, PeachScript approved these changes

2022-12-15 03:21 UTC, merged

2022-12-15 03:29 UTC, xiaohuoni commented
辟起太温暖了，我哭死