feat: Toc component scroll transition when click
umijs/dumi pull request #1303
Opened 2022-11-21 14:54 UTC by fengxinhhh

### 🤔 这个变动的性质是？/ What is the nature of this change?

- [ ] 新特性提交 / New feature
- [ ] bug 修复 / Fix bug
- [ ] 样式优化 / Style optimization
- [ ] 代码风格优化 / Code style optimization
- [ ] 性能优化 / Performance optimization
- [ ] 构建优化 / Build optimization
- [ ] 网站、文档、Demo 改进 / Website, documentation, demo improvements
- [ ] 重构代码或样式 / Refactor code or style
- [ ] 测试相关 / Test related
- [ ] 其他 / Other

### 🔗 相关 Issue / Related Issue

基于此条新增Toc的pr，在原有Toc组件基础上增加滚动过渡效果。

https://github.com/umijs/dumi/pull/1295

### 💡 需求背景和解决方案 / Background or solution

采用 提前计算落差高度，通过`requestAnimationFrame` 一次动画执行35次完成过渡。

### 📝 更新日志 / Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

2022-11-22 02:10 UTC, PeachScript requested changes
1. CI 挂了需要修复，应该是 pnpm-lock.yaml 没更新导致的
2. package.json 的格式及依赖顺序不对，请使用 `pnpm i xx -S -w` 来增加依赖，而不是手动改 package.json
3. 用成熟的三方库实现动画滚动而不是自己实现，这样会增加维护成本：https://www.npmjs.com/package/animated-scroll-to

2022-11-22 09:43 UTC, fengxinhhh commented
1. 已更新`package.json`、`pnpm-lock.yaml`
2. 通过`animated-scroll-to` 库实现过渡滚动~

2022-11-22 11:53 UTC, PeachScript commented on src/client/theme-default/slots/Toc/index.tsx
> +    console.log(newTop)
```suggestion
```

2022-11-22 11:53 UTC, PeachScript commented on src/client/theme-default/slots/Toc/index.tsx
> +    })
代码要格式化

2022-11-22 11:53 UTC, PeachScript commented on src/client/theme-default/slots/Toc/index.tsx
> +  const scrollTo = (newTop: number) => {
这个函数不需要生命在组件内，避免 re-render 消耗

2022-11-22 11:53 UTC, PeachScript commented on src/client/theme-default/slots/Toc/index.tsx
> +  const scrollToByIndex = (h2Index: number) => {
用 useCallback 声明回调函数

2022-11-22 11:53 UTC, PeachScript commented on src/client/theme-default/slots/Toc/index.tsx
> -                      href={link}
链接要保留 + preventDefault，否则 url 不会更新，用户不能复制链接了

2022-11-22 12:29 UTC, fengxinhhh commented
已修改，麻烦再review下看看还有没有什么问题哈

2022-11-22 13:02 UTC, PeachScript commented on src/client/theme-default/slots/Toc/index.tsx
> -                      href={link}
> 链接要保留 + preventDefault，否则 url 不会更新，用户不能复制链接了

@fengxinhhh 试了下 preventDefault 也不会更新 url 了，得想想其他方案

2022-11-23 11:01 UTC, PeachScript commented
@fengxinhhh  预览链接试了下不太对，点击以后 hash 没有更新，这个思路试试看：
1. Toc 里改用 Link 标签来跳转 hash，天然就是 pushState
2. DumPage 里的跳转用 animatedScrollTo 来跳：https://github.com/umijs/dumi/blob/e68fa97a7d3ab175f81ede396b543f6e44b3cb89/src/client/theme-api/DumiPage.tsx#L27

2022-11-23 13:02 UTC, fengxinhhh commented
已修改。

1. 采用`dumi` 中的 `Link` component做锚点hash change
2. 修改了原 `DumiPage ` 的scroll方式

2022-11-23 13:31 UTC, PeachScript commented
> 

Toc 里的 scroll 还需要保留吗，我理解 hash 变更后 DumiPage 里的 scroll 也会触发？

2022-11-23 13:38 UTC, fengxinhhh commented
有道理，因为我只关注了`Toc`组件本身这一块实现，不清楚是有监听的，这样`Toc`里scroll的逻辑确实不需要了

2022-11-24 01:49 UTC, PeachScript commented on src/client/theme-default/slots/Toc/index.tsx
> +                    {
这一层花括号应该不需要

2022-11-24 01:51 UTC, PeachScript commented on src/client/theme-default/slots/Toc/index.tsx
> +
```suggestion
```

2022-11-24 09:01 UTC, fengxinhhh commented
不好意思，疏忽了，有点粗心

2022-11-24 09:01 UTC, fengxinhhh commented
@PeachScript 更新了

2022-11-24 09:22 UTC, PeachScript commented
@fengxinhhh PR 没问题了，但需要等我验证完和  antd 站点的 scroll 是否冲突，再合并发版，感谢 ❤️

2022-11-24 10:45 UTC, fengxinhhh commented
@PeachScript OK~之前pr前也是看的 `ant-design` 貌似用的`Tabs` component自己实现的Toc，最早scroll也是参考那一块的，有任何需要改进的地方随时comment。

另外，已在掘金通过小聪哥get到您的知乎，吸粉了😄

2022-11-25 06:51 UTC, PeachScript approved these changes
+1

2022-11-25 06:52 UTC, merged