style: add rtlSwitch margin style
umijs/dumi pull request #1305
Opened 2022-11-21 16:11 UTC by fengxinhhh

### 🤔 这个变动的性质是？/ What is the nature of this change?

- [ ] 新特性提交 / New feature
- [ ] bug 修复 / Fix bug
- [ ] 样式优化 / Style optimization
- [ ] 代码风格优化 / Code style optimization
- [ ] 性能优化 / Performance optimization
- [ ] 构建优化 / Build optimization
- [ ] 网站、文档、Demo 改进 / Website, documentation, demo improvements
- [ ] 重构代码或样式 / Refactor code or style
- [ ] 测试相关 / Test related
- [ ] 其他 / Other

### 💡 需求背景和解决方案 / Background or solution

在同时出现多语言、RTL元素时，边距重合，如图：

![image](https://user-images.githubusercontent.com/78004597/203103599-4020b670-f396-4367-9d42-746100095d20.png)

![image](https://user-images.githubusercontent.com/78004597/203103676-649bc39f-cc94-422f-9149-6160eee2c39b.png)

故在rltSwitch component中添加相关样式。

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

2022-11-22 02:06 UTC, PeachScript requested changes

2022-11-22 02:06 UTC, PeachScript commented on src/client/theme-default/slots/RtlSwitch/index.less
> +  margin-left: 20px;
这样改单有 RTL 时会有问题，可以这么改：

```less
.@{prefix}-lang-switch {
  + & {
    margin-inline-start: 20px;
  }
}
```

2022-11-22 02:06 UTC, PeachScript commented on src/client/theme-default/slots/RtlSwitch/index.less
> +  margin-right: 20px;
用 CSS 逻辑属性，这里不需要了

2022-11-22 09:54 UTC, fengxinhhh commented
已修改

2022-11-23 12:59 UTC, PeachScript approved these changes
+1

2022-11-23 13:00 UTC, merged