feat(markdown): support CodeGroup
umijs/dumi pull request #2059
Opened 2024-03-26 19:07 UTC by Wxh16144

### 🤔 这个变动的性质是？/ What is the nature of this change?

- [x] 新特性提交 / New feature
- [ ] bug 修复 / Fix bug
- [ ] 样式优化 / Style optimization
- [ ] 代码风格优化 / Code style optimization
- [ ] 性能优化 / Performance optimization
- [ ] 构建优化 / Build optimization
- [ ] 网站、文档、Demo 改进 / Website, documentation, demo improvements
- [ ] 重构代码或样式 / Refactor code or style
- [ ] 测试相关 / Test related
- [ ] 其他 / Other

### 🔗 相关 Issue / Related Issue

### 💡 需求背景和解决方案 / Background or solution

extend https://github.com/umijs/dumi/pull/1734

of：https://github.com/umijs/dumi/discussions/1969

### 📝 更新日志 / Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     feat(markdown): support CodeGroup      |
| 🇨🇳 Chinese |      markdown 支持代码组     |

2024-03-27 07:43 UTC, Wxh16144 commented
ready~

2024-03-29 03:13 UTC, PeachScript requested changes

2024-03-29 03:13 UTC, PeachScript commented on src/loaders/markdown/transformer/remarkContainer.ts
> +            value: `<Container type="${node.name}" ${attrs}>`,
`transformAttributes` 的执行结果一定有头部空格

```suggestion
            value: `<Container type="${node.name}"${attrs}>`,
```

2024-03-29 03:13 UTC, PeachScript commented on src/loaders/markdown/transformer/remarkContainer.ts
> +              [SKIP_DEMO_PARSE_SIGN]: true,
这个标记是不是多个空格？

2024-03-29 03:13 UTC, PeachScript commented on src/loaders/markdown/transformer/remarkContainer.ts
> +          .filter((child): child is Code => child.type === 'code')
还能 `xxx is yyy` 学习了👍

不过这里是不是不用指定返回值的，filter 接收的是 boolean，能推导出函数的返回值也是 boolean

2024-04-01 04:28 UTC, Wxh16144 commented on src/client/theme-default/styles/mixins/tabs.less
> +.default-tabs(@prefix-cls: @prefix) {
done

2024-04-02 08:40 UTC, merged