[WIP] fix: preset-vue
umijs/dumi pull request #2143
Opened 2024-06-14 10:57 UTC by jeffwcx

### 🤔 这个变动的性质是？/ What is the nature of this change?

- [ ] 新特性提交 / New feature
- [x] bug 修复 / Fix bug
- [ ] 样式优化 / Style optimization
- [ ] 代码风格优化 / Code style optimization
- [ ] 性能优化 / Performance optimization
- [ ] 构建优化 / Build optimization
- [ ] 网站、文档、Demo 改进 / Website, documentation, demo improvements
- [ ] 重构代码或样式 / Refactor code or style
- [ ] 测试相关 / Test related
- [ ] 其他 / Other

### 🔗 相关 Issue / Related Issue
#2141

### 💡 需求背景和解决方案 / Background or solution

+ preset-vue引入的问题
   + webpack 配置导致的`@makotot/ghostui/src/Scrollspy` 引入问题（即从node_modules引入tsx）
   + repository 空字段问题
+ 藉由修复demo中require 引入mjs引发的问题

### 📝 更新日志 / Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   fix preset-vue  |
| 🇨🇳 Chinese |   修复preset-vue   |

2024-06-25 08:12 UTC, Jinbao1001 commented
+1

2024-06-27 12:21 UTC, PeachScript requested changes

2024-06-27 12:39 UTC, jeffwcx commented on src/loaders/markdown/index.ts
> +                  [key]: `{{{import('${path}')}}}`,
这里暂时的异步没关系吧，`expandDemoContext` 那里会await一下。不必要的chunk拆分是什么？

2024-07-04 13:25 UTC, Jinbao1001 commented on src/loaders/markdown/index.ts
> +  conditionNames: ['import', 'default', 'browser'],
conditionNames要不要和项目已有保持一致: ['import', 'require', 'default', 'browser', 'node']

2024-07-08 06:10 UTC, merged

2024-07-29 07:56 UTC, lifegit commented
+1, currently still exists.

fatal - TypeError: Cannot read properties of undefined (reading 'directory')
    at Hook.fn (/ui-pro/node_modules/.pnpm/@dumijs+preset-vue@2.3.0_dumi@2.4.7_@babel+core@7.24.7_@swc+helpers@0.5.1_@types+node@20.5.1__s4uoca4yeixx4ez3l74iass7zu/node_modules/@dumijs/preset-vue/dist/common.js:42:91)
    at /ui-pro/node_modules/.pnpm/@umijs+core@4.3.10/node_modules/@umijs/core/dist/service/service.js:136:38
    at _next10 (eval at create (/ui-pro/node_modules/.pnpm/@umijs+bundler-utils@4.3.10/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:8410), <anonymous>:85:18)
    at eval (eval at create (/ui-pro/node_modules/.pnpm/@umijs+bundler-utils@4.3.10/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:8410), <anonymous>:110:1)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
fatal - A complete log of this run can be found in:
fatal - /ui-pro/myapp/node_modules/.cache/logger/umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues