Wuxh/feat pkg pr new
umijs/dumi pull request #2167
Opened 2024-07-11 13:12 UTC by Wxh16144

### 🤔 这个变动的性质是？/ What is the nature of this change?

- [ ] 新特性提交 / New feature
- [ ] bug 修复 / Fix bug
- [ ] 样式优化 / Style optimization
- [ ] 代码风格优化 / Code style optimization
- [ ] 性能优化 / Performance optimization
- [ ] 构建优化 / Build optimization
- [ ] 网站、文档、Demo 改进 / Website, documentation, demo improvements
- [ ] 重构代码或样式 / Refactor code or style
- [x] 测试相关 / Test related
- [ ] 其他 / Other

### 🔗 相关 Issue / Related Issue

### 💡 需求背景和解决方案 / Background or solution

对每个 PR 进行一个持续发布~ see more: https://github.com/stackblitz-labs/pkg.pr.new

### 📝 更新日志 / Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     --      |
| 🇨🇳 Chinese |      add pkg-pr-new     |

2024-07-11 13:14 UTC, Wxh16144 commented on .github/workflows/pkg.pr.new.yml
> +        run: npx -p @wuxh/pkg-pr-new@0.0.15-fork.1 \
这里 pkg 有点问题，我先 fork 一份修复试试水


写了一个文章说明：https://juejin.cn/post/7389950978244935721

2024-07-11 13:45 UTC, Wxh16144 commented
缓存pi匹配的的 key 是有问题的，需要调整一下

<img width="2056" alt="image" src="https://github.com/umijs/dumi/assets/32004925/cb966037-60ed-48c8-8f30-2d47d073581e">

2024-07-11 18:59 UTC, Wxh16144 commented
我在我 fork 的仓库测试成功，到 https://github.com/Wxh16144/_dumi/runs/27339709179 可以查看到有 3 个 examples。

但是点击打开 example 后， stackblitz 也能正常安装依赖，但是 dev 启动不成功。（可以试一下

然后我下载到本地，安装依赖后又能正常启动...

2024-07-11 19:03 UTC, Wxh16144 commented
> 但是点击打开 example 后， stackblitz 也能正常安装依赖，但是 dev 启动不成功。（可以试一下

每个 example 的报错截图...

1.  __@examples/normal__
![image](https://github.com/user-attachments/assets/667654d7-4ae8-46f0-892a-094652425c73)

2. __@examples/vue__
![image](https://github.com/user-attachments/assets/0936c140-573e-4b63-8d94-d2b40e10b3bf)

3. __@examples/mobile__
![image](https://github.com/user-attachments/assets/58a1dca3-3c0c-4ac4-a86d-693753dbd50e)

2024-07-12 02:45 UTC, PeachScript requested changes

2024-07-12 02:45 UTC, PeachScript commented on scripts/pkg-pr-new.ts
> +    ['-p', '@wuxh/pkg-pr-new@0.0.15-fork.1', 'pkg-pr-new', ...params],
为啥会有这个包名 `@wuxh/pkg-pr-new@0.0.15-fork.1`

2024-07-12 02:45 UTC, PeachScript commented on scripts/prepare-examples.ts
> +    // const pkgJson = require(example);
删掉？

2024-07-12 02:53 UTC, Wxh16144 commented on scripts/pkg-pr-new.ts
> +    ['-p', '@wuxh/pkg-pr-new@0.0.15-fork.1', 'pkg-pr-new', ...params],
有个前因后果：https://github.com/stackblitz-labs/pkg.pr.new/pull/142

不过可以等我在 antd 那边先测试一下，然后看 pkg.pr.new 那边作者是否合并这个 PR

2025-05-09 03:28 UTC, PeachScript approved these changes
+1

2025-05-09 03:28 UTC, merged