fix(theme): scrollTop compatible in Edge
umijs/dumi pull request #299
Opened 2020-08-26 13:55 UTC by mortalYoung

### 简介
- 修复锚点在 Edge 无效的问题

### 主要变更
- 锚点滚动用 `window.scrollTo` 来实现，查了一下 兼容性还可以，只不过 `Edge` 貌似不支持 `smooth` 滚动
- [scrollTo的MDN](https://developer.mozilla.org/zh-CN/docs/Web/API/Window/scrollTo)

2020-08-27 10:43 UTC, PeachScript commented
CI 挂了

2020-08-29 13:42 UTC, PeachScript requested changes

2020-08-29 13:42 UTC, PeachScript commented on packages/preset-dumi/src/theme/components/AnchorLink.test.tsx
> +    window.scrollTo = jest.fn((x, y) => {
在 case 执行结束需要把这个方法恢复下

2020-08-29 13:47 UTC, PeachScript commented
话说 `scrollTo` 是不是不支持非 Webkit 版本的 Edge？如果是的话这个兼容性还是不够的

2020-08-30 02:22 UTC, mortalYoung commented
> 话说 `scrollTo` 是不是不支持非 Webkit 版本的 Edge？如果是的话这个兼容性还是不够的

支持的 只是不支持 `ScrollToOptions`

2020-08-30 02:22 UTC, mortalYoung commented
但是 `IE` 上还是有一些其他小问题 我一起 fix 掉吧

2020-08-30 15:10 UTC, PeachScript requested changes

2020-08-30 15:10 UTC, PeachScript commented on packages/preset-dumi/src/theme/components/AnchorLink.test.tsx
> +  let scrollTo: any;
这个文件里的 case 没改过 `window.scrollTo`，为啥需要声明？

2020-08-30 15:10 UTC, PeachScript commented on packages/theme-default/src/layout.tsx
> +          msGridColumn: `${2 * (index % 3) + 1}`,
太拼了👀 改 flex box？

2020-08-31 09:45 UTC, mortalYoung commented on packages/preset-dumi/src/theme/components/AnchorLink.test.tsx
> +  let scrollTo: any;
因为我发现这个文件的 case 执行的时候会报错 `Not implemented: window.scrollTo` 这样的错 所以我也觉得应该需要 mock 一个 虽然这个报错好像并不会 abort case

2020-08-31 09:50 UTC, mortalYoung commented on packages/theme-default/src/layout.tsx
> +          msGridColumn: `${2 * (index % 3) + 1}`,
我觉得要不暂时不考虑 IE 吧
因为我发现 IE 下 Previewer 的渲染貌似有问题 只要有 Previewer 的页面貌似都崩了  然后在 IE 默认渲染模式是 IE7
还得加 `X-UA-Compatible` 考虑以后再慢慢做 先把 Edge 兼容了？

2020-08-31 15:05 UTC, PeachScript commented on packages/theme-default/src/layout.tsx
> +          msGridColumn: `${2 * (index % 3) + 1}`,
嗯，我们兼容 Edge 13+ 即可，和 Umi 的默认兼容性保持一致

2020-09-01 16:09 UTC, PeachScript approved these changes

2020-09-01 16:14 UTC, merged