feat: auto generate component api via types & comments
umijs/dumi pull request #354
Opened 2020-10-23 09:44 UTC by PeachScript

### 主要变更
支持基于 TypeScript 类型定义和 JS Doc 注解生成组件 API 元数据，并提供给主题系统做渲染。

### 详细内容
- 基于 react-docgen-typescript 解析组件 API + 追加多语言组件描述方言
- 新增 `useApiData` 主题 API，用于获取 API 元数据
- 默认主题新增 `API` 内置组件，用于渲染 API 元数据，该组件可通过 theme 约定进行自定义
- 添加 API 解析的文档和范例到实验室

更多信息参考下方文档预览链接。

## 相关 issue
#111

2020-10-24 03:31 UTC, mortalYoung requested changes

2020-10-24 03:31 UTC, mortalYoung commented on docs/lab/index.md
> +Before API generate, we need to write correct TypeScript definitions and doc comments, to make sure dumi can parse them. For example the `Hello` component:
```suggestion
For generating API automatically, we need to ensure that dumi can devise the content of API via correct TypeScript definitions and doc comments. For example the `Hello` component:
```

2020-10-24 03:31 UTC, mortalYoung commented on docs/lab/index.md
> +Base on the correct source code, we can render the API table via `API` builtin component in Markdown:
```suggestion
Based on the correct source code, we can render the API table via `API` builtin component in Markdown:
```

2020-10-24 03:31 UTC, mortalYoung commented on docs/lab/index.md
> +### Control API table render
```suggestion
### Control API table rendering
```

2020-10-24 03:31 UTC, mortalYoung commented on docs/lab/index.md
> +Like other builtin components, we can also override the `API` builtin component via theme API, just need to create `.dumi/theme/builtins/API.tsx` (local theme), or create a theme package that contain
```suggestion
Like other builtin components, we can also override the `API` builtin component via theme API, just need to create a `.dumi/theme/builtins/API.tsx` (local theme), or create a theme package that contains the `API.tsx`, and import `useApiData` hook from `dumi/theme`, then we can control rendering as you like. Please refer the implementation of default [API component](https://github.com/umijs/dumi/blob/master/packages/theme-default/src/builtins/API.tsx).
```

2020-10-24 10:30 UTC, HeyiMaster approved these changes

2020-10-24 15:46 UTC, PeachScript commented on packages/preset-dumi/src/api-parser/fixtures/raw/forwardRef.tsx
> +  // FIXME: ts type error
没太理解，这个 case 是用来覆盖 ref 透传的场景的

2020-10-25 01:51 UTC, mortalYoung commented on packages/preset-dumi/src/api-parser/fixtures/raw/forwardRef.tsx
> +  // FIXME: ts type error
你这里的类型错误是因为组件的参数不可以是 ref

2020-10-26 04:13 UTC, PeachScript commented on packages/preset-dumi/src/api-parser/fixtures/raw/forwardRef.tsx
> +  // FIXME: ts type error
get 到了…

上次 debug 了一下似乎不是这个原因，更像是 forwardRef 传下去的泛型和 props 内的始终对不上导致的，花了挺多时间但还是没解决，所以先 ignore 了；另外，ref 命名是需要保留的，否则 forwadRef 就没体现了

2020-10-26 12:39 UTC, mortalYoung approved these changes

2020-10-28 06:03 UTC, PeachScript commented
新增内容：
1. 支持通过传递 exports 参数控制要渲染的 API 导出：`<API exports='["default", "Other"]'></API>`
2. 为 API 表格生成锚点列表

2020-10-28 10:55 UTC, merged