Feat umi ui
umijs/dumi pull request #378
Opened 2020-11-11 17:04 UTC by bluescurry

1. 修改 dumi 关于对接 umi-ui 的文档错误
2. applyCodeBlock 方法中增加 previewUrl 参数用来设置预览 url 地址

2020-11-12 02:58 UTC, PeachScript requested changes
感觉可以把 `config.sitemap.hostname` 拎出来？这样我们其实可以为用户直接生成 `previewUrl`

2020-11-12 02:58 UTC, PeachScript commented on packages/preset-dumi/src/transformer/remark/previewer.ts
> +      previewUrl: props.previewUrl || props.previewurl,
这里统一 `previewUrl` 吧，目前 `code` 属性的解析会把驼峰变成中横线，还没找到优雅的方式，得特殊处理下：https://github.com/umijs/dumi/blob/master/packages/preset-dumi/src/transformer/remark/jsxify.ts#L19

2020-11-15 12:29 UTC, bluescurry commented on packages/preset-dumi/src/transformer/remark/previewer.ts
> +      previewUrl: props.previewUrl || props.previewurl,
我试了一下，code 属性设置 `preview-url` ，previewer.js 中拿到的是 `props['preview-url']`；设置 `previewUrl`，previewer.js 中拿到的是 `props.previewurl`。是不是和预期不太符合？

2020-11-15 12:38 UTC, bluescurry commented
> 感觉可以把 `config.sitemap.hostname` 拎出来？这样我们其实可以为用户直接生成 `previewUrl`

我认为是可行的。不过我觉得最好还是要支持自定义 previewUrl 配置~

2020-11-15 12:47 UTC, bluescurry commented on packages/preset-dumi/src/transformer/remark/previewer.ts
> +      previewUrl: props.previewUrl || props.previewurl,
> 这里统一 `previewUrl` 吧，目前 `code` 属性的解析会把驼峰变成中横线，还没找到优雅的方式，得特殊处理下：https://github.com/umijs/dumi/blob/master/packages/preset-dumi/src/transformer/remark/jsxify.ts#L19

get 到你的点了，我特殊处理一下。。。

2020-11-19 02:41 UTC, bluescurry commented on packages/preset-dumi/src/transformer/remark/previewer.ts
> +      previewUrl: props.previewUrl || props.previewurl,
> 这里统一 `previewUrl` 吧，目前 `code` 属性的解析会把驼峰变成中横线，还没找到优雅的方式，得特殊处理下：https://github.com/umijs/dumi/blob/master/packages/preset-dumi/src/transformer/remark/jsxify.ts#L19

请问您看到我的回复了吗，非常感谢如果您能回复我，我认为预览这个功能很重要，用户可以提前体验到这个区块的所有功能，以确定这个区块是否是自己想要的

2020-11-19 03:03 UTC, PeachScript commented on packages/preset-dumi/src/transformer/remark/previewer.ts
> +      previewUrl: props.previewUrl || props.previewurl,
明白，我今天把 previewUrl 这个问题补进 PR

2020-11-19 03:06 UTC, bluescurry commented on packages/preset-dumi/src/transformer/remark/previewer.ts
> +      previewUrl: props.previewUrl || props.previewurl,
> 明白，我今天把 previewUrl 这个问题补进 PR

非常感谢😁

2020-11-19 16:29 UTC, PeachScript commented
`previewUrl` 的特殊处理加上了，不过没太理解为何要把 `previewUrl` 传给 `Previewer`，应该只需要元数据里面有就够了

2020-11-20 01:43 UTC, bluescurry commented
> `previewUrl` 的特殊处理加上了，不过没太理解为何要把 `previewUrl` 传给 `Previewer`，应该只需要元数据里面有就够了

我的想法是在创建 assets.json 时，为区块增加 previewUrl 属性，用于在 umi-ui 使用区块时的预览功能，我看源码的时候发现是在 previewer.ts 中进行处理的，所以我修改了 previewer.ts，您看是有我的理解有误吗？在 previewer.ts 做处理是正确的吗

2020-11-20 02:12 UTC, PeachScript commented
> 我的想法是在创建 assets.json 时，为区块增加 previewUrl 属性，用于在 umi-ui 使用区块时的预览功能，我看源码的时候发现是在 previewer.ts 中进行处理的，所以我修改了 previewer.ts，您看是有我的理解有误吗？在 previewer.ts 做处理是正确的吗

明白了，是我想岔了👍

2020-11-20 02:12 UTC, PeachScript approved these changes

2020-11-20 02:14 UTC, merged