fix ssr
umijs/dumi pull request #625
Opened 2021-04-03 09:09 UTC by itellyou-com

`color = document.documentElement.getAttribute(COLOR_ATTR_NAME) as PrefersColorValue;`
ColorChanger 类在给 color 赋值的时候使用了 document ，如果在SSR环境下 document 是undefined，导致渲染错误

解决：
在构造函数内  `if(typeof document === undefined) return` 判断，并把 color的 赋值放在判断后面

### 🤔 这个变动的性质是？/ What is the nature of this change?

- [ ] 新特性提交 / New feature
- [x] bug 修复 / Fix bug
- [ ] 样式优化 / Style optimization
- [ ] 代码风格优化 / Code style optimization
- [ ] 性能优化 / Performance optimization
- [ ] 构建优化 / Build optimization
- [ ] 网站、文档、Demo 改进 / Website, documentation, demo improvements
- [ ] 重构代码或样式 / Refactor code or style
- [ ] 测试相关 / Test related
- [ ] 其他 / Other

| Language   | Changelog |
| ---------- | --------- |
| 🇨🇳 Chinese |           |

2021-04-03 16:14 UTC, mortalYoung commented on packages/preset-dumi/src/theme/hooks/usePrefersColor.ts
> +    if(typeof document === undefined) return
`umi` 提供了一个 `isBrowser` 的方法用来做环境变量
可以看看能不能用 `isBrowser` 来做判断

2021-04-04 00:43 UTC, itellyou-com commented on packages/preset-dumi/src/theme/hooks/usePrefersColor.ts
> +    if(typeof document === undefined) return
可以，替换了

2021-04-06 01:28 UTC, xrkffgg commented on packages/preset-dumi/src/theme/hooks/usePrefersColor.ts
> +  color:PrefersColorValue = "auto"
```suggestion
  color:PrefersColorValue = 'light'
```

2021-04-06 01:56 UTC, PeachScript requested changes

2021-04-06 01:56 UTC, PeachScript commented on packages/preset-dumi/src/theme/hooks/usePrefersColor.ts
> +import { isBrowser } from 'umi'
```suggestion
import { isBrowser } from 'dumi';
```

2021-04-06 01:56 UTC, PeachScript commented on packages/preset-dumi/src/theme/hooks/usePrefersColor.ts
> +    if(!isBrowser()) return
```suggestion
    if (!isBrowser()) return;
```

2021-04-06 14:38 UTC, PeachScript commented on packages/preset-dumi/src/theme/hooks/usePrefersColor.ts
> +import { isBrowser } from 'dumi';
```suggestion
import { isBrowser } from 'umi';
```

2021-04-06 15:02 UTC, PeachScript approved these changes

2021-04-06 15:02 UTC, merged