feat: add search-bar for doc mode, https://github.com/umijs/dumi/issues/373
umijs/dumi pull request #678
Opened 2021-05-10 09:05 UTC by suedar

### 🤔 这个变动的性质是？/ What is the nature of this change?

- [☑️] 新特性提交 / New feature

### 🔗 相关 Issue / Related Issue

https://github.com/umijs/dumi/issues/373

### 📝 更新日志 / Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      add search-bar for doc mode     |
| 🇨🇳 Chinese |    为 `doc mode` 添加搜索框       |

2021-05-10 09:10 UTC, xrkffgg commented on packages/theme-default/src/components/SideMenu.tsx
> +  console.log(meta)
😂😂😂

2021-05-10 09:10 UTC, xrkffgg commented on packages/theme-default/package.json
> +    "classnames": "^2.3.1",
@PeachScript 要用这个吗？是挺方便的，我看之前都没用，dark 的时候，我就没用。。。

2021-05-10 09:19 UTC, lbwa requested changes

2021-05-10 09:19 UTC, lbwa commented on packages/theme-default/src/components/SearchBar.tsx
> +import c from 'classnames';
接着 @xrkffgg 关于依赖的问题，即使使用 classnames ，也别用单字符做变量名吧

2021-05-11 03:38 UTC, PeachScript commented on packages/theme-default/package.json
> +    "classnames": "^2.3.1",
问题不大，我之前是因为用的地方太少了，引一个库不划算

2021-05-12 03:26 UTC, PeachScript commented
感觉 UI 可以优化下，大家一起看看：
1. 侧边栏的拥挤程度已经很高了，搜索框是不是默认收起会好一些，或者有没有更好的布局方案，哪怕大刀阔斧一些
2. 搜索的结果替代侧边栏子项的方式会比较奇怪，是不是仍旧采用 popup 的形态会好一些

2021-05-12 07:08 UTC, suedar commented
这样的处理参考自 [docz](https://www.docz.site/) ，或者你们有更好的想法。
popup 会有点奇怪 可能有 header 的时候会比较好一点

2021-07-05 07:47 UTC, birdycn commented
怎么使用搜索呢？？

2021-07-05 13:26 UTC, xrkffgg commented
cc @suedar

2021-07-07 10:08 UTC, suedar commented
有点久了这个，之前的场景是复用原搜索框，由于 `mode: doc` 没有搜索框，将 `mode: site` 右上角的搜索框放到 `doc` 上了。
现在可能有点变化，我有空再看看。

2023-01-28 09:31 UTC, PeachScript commented
❤️ 感谢贡献，dumi v1 不再更新，PR 将会关闭；dumi v2 已发布，欢迎继续参与 dumi 的建设，https://d.umijs.org/

2023-01-28 09:31 UTC, closed without merging