add a site using dumi
umijs/dumi pull request #702
Opened 2021-05-25 03:44 UTC by artdong

### 🤔 这个变动的性质是？/ What is the nature of this change?

- [ √ ] 网站、文档、Demo 改进 / Website, documentation, demo improvements

### 💡 需求背景和解决方案 / Background or solution

add a demo using dumi.

### 📝 更新日志 / Changelog

add a demo called react-org-tree.

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

2021-05-25 03:48 UTC, PeachScript requested changes
修改这个脚本 https://github.com/umijs/dumi/blob/master/scripts/update-readme-user.js#L72 ，然后本地执行下，再将 `README.md` 的变更提交

2021-05-25 03:49 UTC, PeachScript commented on packages/dumi/README.md
> +        <img src="https://avatars3.githubusercontent.com/u/9441414?s=200&v=4" width="42" />
有自己的 LOGO 吗，用 React 的不合适

2021-05-25 06:19 UTC, artdong commented on packages/dumi/README.md
> +        <img src="https://avatars3.githubusercontent.com/u/9441414?s=200&v=4" width="42" />
logo已变更

2021-05-25 06:23 UTC, xrkffgg commented on scripts/update-readme-user.js
> +    logo: 'https://github.com/artdong/react-org-tree/blob/master/img/logo.svg',
这个看不到

2021-05-25 06:46 UTC, artdong commented on scripts/update-readme-user.js
> +    logo: 'https://github.com/artdong/react-org-tree/blob/master/img/logo.svg',
已更改

2021-05-25 12:01 UTC, artdong commented
改了，怎么流程还没走呢


发自我的iPhone

------------------ Original ------------------
From: xrkffgg ***@***.***&gt;
Date: Tue,May 25,2021 2:24 PM
To: umijs/dumi ***@***.***&gt;
Cc: art ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [umijs/dumi] add a site using dumi (#702)





 
@xrkffgg commented on this pull request.
 
 
In scripts/update-readme-user.js:
 &gt; @@ -70,6 +70,11 @@ const users = [      url: 'https://v2.formilyjs.org/',      logo: 'https://img.alicdn.com/imgextra/i2/O1CN01Kq3OHU1fph6LGqjIz_!!6000000004056-55-tps-1141-150.svg',    }, +  { +    name: 'react-org-tree', +    url: 'https://artdong.github.io/react-org-tree/', +    logo: 'https://github.com/artdong/react-org-tree/blob/master/img/logo.svg',  
这个看不到
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-05-26 05:43 UTC, PeachScript commented on scripts/update-readme-user.js
> +    logo: 'https://github.com/artdong/react-org-tree/blob/master/img/logo.svg',
> 已更改

没重新执行脚本，预览链接里图片还是挂的

2021-05-26 06:08 UTC, artdong commented on scripts/update-readme-user.js
> +    logo: 'https://github.com/artdong/react-org-tree/blob/master/img/logo.svg',
> 没重新执行脚本，预览链接里图片还是挂的

现在应该可以了

2021-05-27 02:37 UTC, merged