fix: fix module not found problem
umijs/dumi pull request #955
Opened 2021-11-22 12:06 UTC by binyellow

### 🤔 这个变动的性质是？/ What is the nature of this change?

- [ ] 新特性提交 / New feature
- [x] bug 修复 / Fix bug
- [ ] 样式优化 / Style optimization
- [ ] 代码风格优化 / Code style optimization
- [ ] 性能优化 / Performance optimization
- [ ] 构建优化 / Build optimization
- [ ] 网站、文档、Demo 改进 / Website, documentation, demo improvements
- [ ] 重构代码或样式 / Refactor code or style
- [ ] 测试相关 / Test related
- [ ] 其他 / Other

### 🔗 相关 Issue / Related Issue

### 💡 需求背景和解决方案 / Background or solution

**When dumi is upgraded to 1.1.32, the error is reported as follows**, The test found that ./Tree.less satisfies the style requirements
```js
This dependency was not found:

* rc-tree/assets/index.less in ./node_modules/dumi-theme-default/es/builtins/Tree.js

To install it, you can run: npm install --save rc-tree/assets/index.less
```

### 📝 更新日志 / Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      fix module not found problem     |
| 🇨🇳 Chinese |      修复模块未找到问题     |

2021-11-23 06:41 UTC, PeachScript commented on packages/theme-default/src/builtins/Tree.tsx
> +import  Tree from 'rc-tree';
多了个空格，文件格式化一下？

2021-11-23 06:41 UTC, PeachScript commented on packages/theme-default/src/builtins/Tree.tsx
> -import 'rc-tree/assets/index.less'
@xrkffgg 评估下这个 less 是否有用到？这个引入确实会影响 rc-tree 项目的文档构建，自己依赖自己、但 dumi 没建立 `rc-tree/assets` 的 alias🤦‍♂️

2021-11-23 06:55 UTC, binyellow commented on packages/theme-default/src/builtins/Tree.tsx
> +import  Tree from 'rc-tree';
1

2021-11-23 08:18 UTC, xrkffgg commented on packages/theme-default/src/builtins/Tree.tsx
> -import 'rc-tree/assets/index.less'
去掉 会影响 样式的，不过可以把一些 必要的 样式 拿进来

2021-11-23 08:18 UTC, xrkffgg commented on packages/theme-default/src/builtins/Tree.tsx
> -import 'rc-tree/assets/index.less'
cc @binyellow

2021-11-23 08:20 UTC, xrkffgg requested changes
import 'rc-tree/assets/index.less'  去掉后 样式会乱，可以拿到 Tree.less 内

2021-11-23 08:22 UTC, binyellow commented on packages/theme-default/src/builtins/Tree.tsx
> -import 'rc-tree/assets/index.less'
嗯，我昨晚测了下3层的树，看样式是ok的。我待会仔细对照看下，到时候lg review一下

2021-11-23 08:33 UTC, xrkffgg commented on packages/theme-default/src/builtins/Tree.tsx
> -import 'rc-tree/assets/index.less'
我看目前 这个 预览 地址里的 是不太一样

2021-11-23 08:35 UTC, binyellow commented on packages/theme-default/src/builtins/Tree.tsx
> -import 'rc-tree/assets/index.less'
嗯 我 看老哥是迁移了部分rc-tree的样式在Tree.less里，是基于打包大小考虑吗？是否可以直接全量引入？

2021-11-23 08:57 UTC, xrkffgg commented on packages/theme-default/src/builtins/Tree.tsx
> -import 'rc-tree/assets/index.less'
之前是 引的 antd 的，样式很多是 antd 的。我觉得 可以看一下 视觉差异 把 需要的 补上就行，不用全量

2021-11-23 09:39 UTC, binyellow commented on packages/theme-default/src/builtins/Tree.tsx
> -import 'rc-tree/assets/index.less'
嗯  引入了部分必要样式

2021-11-23 16:40 UTC, xrkffgg commented
![image](https://user-images.githubusercontent.com/29775873/143066078-c287a1ea-deaf-445e-ad4d-cb84bb12911c.png)

正常白底 也是有 间隙的，黑底 比较明显。  样式再更进 一下~ @binyellow

2021-11-24 01:27 UTC, binyellow commented
> ![image](https://user-images.githubusercontent.com/29775873/143066078-c287a1ea-deaf-445e-ad4d-cb84bb12911c.png)
> 
> 正常白底 也是有 间隙的，黑底 比较明显。 样式再更进 一下~ @binyellow

好的 老哥

2021-11-24 08:45 UTC, PeachScript commented
@xrkffgg 部署链接好像不更新了 👀

2021-11-24 14:59 UTC, xrkffgg commented on packages/theme-default/package.json
> +    "rc-tree": "^5.3.0"
```suggestion
    "rc-tree": "^5.2.0"
```

2021-11-24 15:12 UTC, xrkffgg approved these changes

2021-11-25 02:22 UTC, merged